export {MainHeader} from "./mainHeader/ui/MainHeader"
export {Address} from "./address/ui/Address"
export {Number} from "./number/ui/Number"
export {HeaderTop} from "./headerTop/HeaderTop"
export {Socials} from "./socials/Socials"
export {Footer} from "./footer/Footer"
